SST2017/Models/IdentityModels.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace SST2017.Models
{
    public class AppUser : IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }
}

SST2017/ViewModels/AccountViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SST2017.ViewModels
{

    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }

    public class ManageUserViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

}

SST2017/Controllers/AboutController.cs
using System.Web.Mvc;

namespace SST2017.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

SST2017/Controllers/BlogController.cs
using System.Web.Mvc;


namespace SST2017.Controllers
{
    
    
    public class BlogController : Controller
    {
    }
}

SST2017/Controllers/ContactController.cs
using System.Web.Mvc;

namespace SST2017.Controllers
{
    public class ContactController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

SST2017/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SST2017.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SST2017/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BootstrapSite1.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult OnCall()
        {
            return View();
        }

        public ActionResult Process(string userid, string password)
        {
            if (userid == "chesapeake" && password == "1223")
                return View("Chesapeake");

            return RedirectToAction("OnCall");
        }
    }
}

SST2017/Controllers/OtherController.cs
using System.Web.Mvc;


namespace SST2017.Controllers
{
    
    
    public class OtherController : Controller
    {
        
        public ActionResult FullWidth()
        {
            return View();
        }
        
        public ActionResult SideBar()
        {
            return View();
        }
        
        public ActionResult Faq()
        {
            return View();
        }
        
        public ActionResult FourOhFour()
        {
            return View();
        }
    }
}

SST2017/Controllers/PortfolioController.cs
using System.Web.Mvc;


namespace SST2017.Controllers
{
    
    
    public class PortfolioController : Controller
    {
        
        public ActionResult OneColumn()
        {
            return View();
        }
        
        public ActionResult TwoColumn()
        {
            return View();
        }
        
        public ActionResult ThreeColumn()
        {
            return View();
        }
        
        public ActionResult FourColumn()
        {
            return View();
        }
        
        public ActionResult SingleItem()
        {
            return View();
        }
    }
}

SST2017/Controllers/ServicesController.cs
using System.Web.Mvc;

namespace SST2017.Controllers
{
    public class ServicesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

SST2017/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "Contact";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Contact <small>We'd Love to Hear From You!</small></h1>
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="active">Contact</li>
            </ol>
        </div>
        <div class="col-lg-12">
            <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
            <iframe width="100%" scrolling="no" height="400px" frameborder="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed" marginwidth="0" marginheight="0"></iframe>
        </div>
    </div><!-- /.row -->
    <div class="row">
        <div class="col-sm-8">
            <h3>Let's Get In Touch!</h3>
            <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            <form action="contact-form-submission.php" method="POST" role="form">
                <div class="row">
                    <div class="form-group col-lg-4">
                        <label for="input1">Name</label>
                        <input type="text" id="input1" class="form-control" name="contact_name">
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="input2">Email Address</label>
                        <input type="email" id="input2" class="form-control" name="contact_email">
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="input3">Phone Number</label>
                        <input type="phone" id="input3" class="form-control" name="contact_phone">
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group col-lg-12">
                        <label for="input4">Message</label>
                        <textarea id="input4" rows="6" class="form-control" name="contact_message"></textarea>
                    </div>
                    <div class="form-group col-lg-12">
                        <input type="hidden" value="contact" name="save">
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-4">
            <h3>Modern Business</h3>
            <h4>A Start Bootstrap Template</h4>
            <p>
                5555 44th Street N.<br>
                Bootstrapville, CA 32323<br>
            </p>
            <p><i class="fa fa-phone"></i> <abbr title="Phone">P</abbr>: (555) 984-3600</p>
            <p><i class="fa fa-envelope-o"></i> <abbr title="Email">E</abbr>: <a href="mailto:feedback@startbootstrap.com">feedback@startbootstrap.com</a></p>
            <p><i class="fa fa-clock-o"></i> <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
            <ul class="list-unstyled list-inline list-social-icons">
                <li class="tooltip-social facebook-link"><a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-page"><i class="fa fa-facebook-square fa-2x"></i></a></li>
                <li class="tooltip-social linkedin-link"><a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-company-page"><i class="fa fa-linkedin-square fa-2x"></i></a></li>
                <li class="tooltip-social twitter-link"><a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a></li>
                <li class="tooltip-social google-plus-link"><a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-page"><i class="fa fa-google-plus-square fa-2x"></i></a></li>
            </ul>
        </div>
    </div><!-- /.row -->
</div>

SST2017/Views/Login/Chesapeake.cshtml
@{
    ViewBag.Title = "Chesapeake";
}

<h2>Chesapeake</h2>

SST2017/Views/Login/OnCall.cshtml
@{
    ViewBag.Title = "OnCall";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Log In</h1>
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="active">Login</li>
            </ol>
        </div>
    </div><!-- /.row -->
    <div class="row">
        <div class="col-sm-8">
            <form action="/Login/Process" method="POST" role="form">
                <div class="row">
                    <div class="form-group col-lg-4">
                        <label for="input1">User ID</label>
                        <input type="text" id="userid" class="form-control" name="userid">
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="input2">Password</label>
                        <input type="password" id="password" class="form-control" name="password">
                    </div>
                    <div class="form-group col-lg-12">
                        <input type="hidden" value="contact" name="save">
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

SST2017/Views/Portfolio/OneColumn.cshtml
@{
    ViewBag.Title = "One Column Portfolio";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                One Column Portfolio
                <small>Showcase Your Work</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                  @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">One Column Portfolio</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Project <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Project <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Project <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Project <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Project <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

SST2017/Views/Portfolio/ThreeColumn.cshtml
@{
    ViewBag.Title = "Three Column Portfolio";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Three Column Portfolio
                <small>Showcase Your Work</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Three Column Portfolio</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

SST2017/Views/Portfolio/TwoColumn.cshtml
@{
    ViewBag.Title = "Two Column Portfolio";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Two Column Portfolio
                <small>Showcase Your Work</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Two Column Portfolio</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
               @Html.ActionLink("Project Name","SingleItem","Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

SST2017/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Modern Business - @ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("~/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/css/modern-business.css")" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
                @Html.ActionLink("SILVER STATE TELECOM", "Index", new { controller = "Home" }, new { @class = "navbar-brand" })
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li id="about">
                       @Html.ActionLink("About", "Index", "About")
                    </li>
                    <li id="services">
                        @Html.ActionLink("Services", "Index", "Services")
                    </li>
                    <li id="contact">
                        @Html.ActionLink("Contact", "Index", "Contact")
                    </li>
                    <li id="portfolio" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="1columnportfolio">
                                @Html.ActionLink("1 Column Portfolio", "OneColumn", "Portfolio")
                            </li>
                            <li id="2columnportfolio">
                                @Html.ActionLink("2 Column Portfolio", "TwoColumn", "Portfolio")
                            </li>
                            <li id="3columnportfolio">
                                @Html.ActionLink("3 Column Portfolio", "ThreeColumn", "Portfolio")
                            </li>
                            <li id="4columnportfolio">
                                @Html.ActionLink("4 Column Portfolio", "FourColumn", "Portfolio")
                            </li>
                            <li id="singleportfolioitem">
                                @Html.ActionLink("Single Portfolio Item", "SingleItem", "Portfolio")
                            </li>
                        </ul>
                    </li>
                    
                    <li id="other" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="onCall">
                                @Html.ActionLink("On Call", "OnCall", "Login")
                            </li>
                            <li id="fullwidthpage">
                                @Html.ActionLink("Full Width Page", "FullWidth", "Other")
                            </li>
                            <li id="sidebarpage">
                                @Html.ActionLink("Sidebar Page", "Sidebar", "Other")
                            </li>
                            <li id="faq">
                                @Html.ActionLink("FAQ", "Faq", "Other")
                            </li>
                            <li id="404">
                                @Html.ActionLink("404", "FourOhFour", "Other")
                            </li>

                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    @RenderBody()

    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="@Url.Content("~/js/bootstrap.js")"></script>
    <script src="@Url.Content("~/js/modern-business.js")"></script>
</body>
</html>